import {createContext, useContext, useReducer} from "react";
import {basketReducer, productReducer} from "./Reducers";
import img from '../assets/images/PikPng.com_perfume-png_1269742.png';

const Basket = createContext();

const Context = ({ children }) => {
    // Change below after add proper data
    const products = [
        /*{
            id: '1',
            name: 'Chanel 1',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, veniam? 1',
            price: 30,
            imgSrc: '../../assets/images/PikPng.com_perfume-png_1269742.png',
            inStock: 8,
            fastDelivery: true,
            ratings: 3,
        },
        {
            id: '2',
            brand: 'Chanel',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, veniam? 2',
            price: 40,
            imgSrc: 'https://w7.pngwing.com/pngs/375/849/png-transparent-eau-de-toilette-armani-perfume-cosmetics-sephora-perfume.png',
            inStock: 0,
            fastDelivery: false,
            ratings: 5,
        },
        {
            id: '3',
            brand: 'Boss',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, veniam? 3',
            price: 50,
            imgSrc: '../../assets/images/PikPng.com_perfume-png_1269742.png',
            inStock: 7,
            fastDelivery: true,
            ratings: 4,
        },
        {
            id: '4',
            brand: 'Jimmy Choo',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, veniam? 4',
            price: 60,
            imgSrc: '../../assets/images/PikPng.com_perfume-png_1269742.png',
            inStock: 9,
            fastDelivery: false,
            ratings: 2,
        },*/

        {
            id: "42",
            brand: "Armani",
            name: "Si",
            price: 100,
            desc: "Giorgio Armani Sì Eau De Parfum – The Perfume For Women Armani SÌ EAU DE PARFUM is a timeless perfume that is whole-hearted and grounded yet turns into a soft trail that lingers",
            imgSrc: `${img}`,
            inStock: 10,
            fastDelivery: true,
            ratings: 5,
        },
        {
            id: "43",
            brand: "Armani",
            name: "Si Passione Intense",
            price: 110,
            desc: "Sì Passione Eau De Parfum Intense, the fragrance for women by Giorgio Armani, captures the vibrating true passion. The iconic Sì signature of blackcurrant nectar is blended with an emphatic floral heart made of a jasmine duo.",
            imgSrc: `${img}`,
            inStock: 4,
            fastDelivery: true,
            ratings: 4,
        },
        {
            id: "44",
            brand: "Armani",
            name: "Stronger With You Intensely",
            price: 90,
            desc: "Discover Emporio Armani's STRONGER WITH YOU INTENSELY. It reflects the personality of today's man in search of an intense, longlasting fragrance that lights up his profound love story.",
            imgSrc: `${img}`,
            inStock: 6,
            fastDelivery: false,
            ratings: 3,
        },
        {
            id: "45",
            brand: "Armani",
            name: "Acqua di Gio",
            price: 70,
            desc: "The Aftershave For Him by Giorgio Armani. A light, distinguished eau de toilette inspired by the fresh sea, warm sun and the richness of the earth. This aquatic, aromatic men’s aftershave opens with a splash of fresh calabrian bergamot, neroli and green tangerine.",
            imgSrc: "https://w7.pngwing.com/pngs/870/764/png-transparent-acqua-di-gio-perfume-eau-de-parfum-armani-eau-de-toilette-uomo.png",
            inStock: 0,
            fastDelivery: true,
            ratings: 5,
        },
        {
            id: "46",
            brand: "Armani",
            name: "My Way",
            price: 120,
            desc: "INTRODUCING MY WAY; THE NEW FEMININE FRAGRANCE BY GIORGIO ARMANI Giorgio Armani, designer of timeless fragrances, unveils its new fragrance; MY WAY. Through meaningful connections to others, one finds the path to the truest version of oneself.",
            imgSrc: "https://flyclipart.com/thumb2/bleu-turquoise-perfume-armani-armani-beauty-uk-136812.png",
            inStock: 1,
            fastDelivery: true,
            ratings: 4,
        },
        {
            id: "54",
            brand: "Chanel",
            name: "COCO MADEMOISELLE L'EAU PRIVÉE",
            price: 150,
            desc: "COCO MADEMOISELLE LEau Privée. The essence of a bold and free woman. A soft and sensual fruity oriental fragrance, especially created for the night.",
            imgSrc: "https://w7.pngwing.com/pngs/984/901/png-transparent-perfume-coco-mademoiselle-chanel-no-5-coco-chanel-perfume-cosmetics-chanel-thumbnail.png",
            inStock: 2,
            fastDelivery: false,
            ratings: 3,
        },
        {
            id: "55",
            brand: "Chanel",
            name: "CHANCE EAU TENDRE",
            price: 120,
            desc: "A composition with a radiant heart intensified by jasmine absolute and rose essence. A dazzling floral-fruity fragrance, a full and tender interpretation with heightened femininity.",
            imgSrc: "https://e7.pngegg.com/pngimages/847/724/png-clipart-coco-mademoiselle-chanel-no-5-lotion-coco-chanel-cosmetics-perfume.png",
            inStock: 3,
            fastDelivery: true,
            ratings: 4,
        },
        {
            id: "56",
            brand: "Chanel",
            name: "GABRIELLE CHANEL",
            price: 120,
            desc: "The new women's fragrance by CHANEL is a luminous composition. Inspired by Gabrielle Chanel, the House of CHANEL perfumer Olivier Polge, working with the CHANEL Laboratory of Creation and Development of Perfumes, composed a solar flower based on a bouquet of 4 white flowers. The fragrance appears to hover weightlessly within the exceptional square bottle, crafted of ultra-thin glass. The 4 transparent sides fade into the background allowing the light-filled fragrance to shine through.",
            imgSrc: "https://e1.pngegg.com/pngimages/54/788/png-clipart-chanel-clear-chanel-perfume-bottle.png",
            inStock: 10,
            fastDelivery: true,
            ratings: 5,
        },
        {
            id: "57",
            brand: "Chanel",
            name: "BLEU DE CHANEL",
            price: 100,
            desc: "CHANEL BLEU DE CHANEL EAU DE PARFUM SPRAY A tribute to masculine freedom in an aromatic-woody fragrance with a captivating trail. A timeless, powerful fragrance housed in an enigmatic blue bottle. The aromatic-woody notes of BLEU DE CHANEL find expression in a full range of shaving and body products.",
            imgSrc: "https://w7.pngwing.com/pngs/317/436/png-transparent-chanel-no-5-perfume-coco-mademoiselle-perfume-miscellaneous-cosmetics-chanel.png",
            inStock: 5,
            fastDelivery: false,
            ratings: 5,
        },
        {
            id: "21",
            brand: "Christian Dior",
            name: "Miss Dior",
            price: 118,
            desc: "A delectable smooth velvet rose as if embroidered with a thousand shimmering colourful flowers. Like an olfactory “millefiori”, freshness and sensuality are intertwined to enhance the most couture fragrance by the House of Dior.",
            imgSrc: "https://w7.pngwing.com/pngs/776/311/png-transparent-perfume-christian-dior-se-miss-dior-j-adore-eau-de-parfum-miss-dior-thumbnail.png",
            inStock: 5,
            fastDelivery: false,
            ratings: 5,
        },
        {
            id: "22",
            brand: "Christian Dior",
            name: "Diorissimo",
            price: 94,
            desc: "As bright as a spring morning, this romantic floral bouquet blossoms with the freshness of lily-of-the-valley, Christian Dior's lucky flower and the emblem of Dior Couture.",
            imgSrc: "https://w7.pngwing.com/pngs/515/568/png-transparent-eau-de-toilette-diorissimo-perfume-christian-dior-se-miss-dior-perfume-miscellaneous-perfume-cosmetics.png",
            inStock: 5,
            fastDelivery: false,
            ratings: 5,
        },
        {
            id: "23",
            brand: "Christian Dior",
            name: "Miss Dior Originale",
            price: 99,
            desc: "In the words of Christian Dior, I created this perfume to wrap each woman in exquisite femininity, as if each of my designs were emerging from the bottle one by one. Born with the New Look in 1947, the house's first perfume incarnates the signature of a great designer in the timeless elegance and refinement of a classic green chypre with galbanum and jasmine",
            imgSrc: "https://e7.pngegg.com/pngimages/963/961/png-clipart-perfume-dior-miss-dior-blooming-bouquet-eau-de-toilette-dior-miss-dior-blooming-bouquet-eau-de-toilette-christian-dior-se-miss-dior-ad.png",
            inStock: 6,
            fastDelivery: true,
            ratings: 1,
        },
        {
            id: "29",
            brand: "Hugo Boss",
            name: "Boss Bottled United",
            price: 57,
            desc: "Inspired by the most intense and joyful moments of celebration in sport, BOSS Bottled United Eau de Parfum for Men combines the freshness of a sport fragrance with the warmth and elegance of the timeless BOSS Bottled signature. Deeply masculine, this oriental aromatic scent is the olfactive encapsulation of celebration and its power to unite us.",
            imgSrc: "https://e7.pngegg.com/pngimages/15/841/png-clipart-perfume-boss-bottled-night-hugo-boss-no-6-night-by-hugo-boss-for-men-edt-100ml-perfume-miscellaneous-cosmetics.png",
            inStock: 6,
            fastDelivery: true,
            ratings: 4,
        },
        {
            id: "30",
            brand: "Hugo Boss",
            name: "Boss Bottled Oud",
            price: 89,
            desc: "BOSS Bottled Oud Eau de Toilette for Men is a magnificent amber fougere, in which spicy, animalic and leather facets are fused with redolent oud woods. Delectable fruit notes of bergamot, apple and plum rest on an aromatic elixir of geranium, clove and cinnamon, fused with rare saffron and evocative labdanum resin.",
            imgSrc: "https://e7.pngegg.com/pngimages/433/94/png-clipart-eau-de-toilette-perfume-hugo-boss-aftershave-tommy-hilfiger-perfume.png",
            inStock: 11,
            fastDelivery: true,
            ratings: 2,
        },
        {
            id: "31",
            brand: "Hugo Boss",
            name: "Boss Bottled",
            price: 100,
            desc: "An intense and refined masculinity is revealed in BOSS Bottled Eau de Parfum. Created for driven, ambitious men ready to take on every challenge that comes their way, this noble composition brings a new intensity to the warmth and vibrancy of the timeless BOSS Bottled signature.",
            imgSrc: "https://w7.pngwing.com/pngs/821/506/png-transparent-perfume-hugo-boss-boss-bottled-intense-woda-toaletowa-tester-eau-de-toilette-gucci-perfume-miscellaneous-cosmetics-boss.png",
            inStock: 7,
            fastDelivery: true,
            ratings: 3,
        },
        {
            id: "47",
            brand: "Jimmy Choo",
            name: "Flash",
            price: 39,
            desc: "Be the shining star at every party by stepping out in the new ultimate accessory from Jimmy Choo, the perfect companion for the party girl in us all.",
            imgSrc: "https://w7.pngwing.com/pngs/721/1003/png-transparent-perfume-jimmy-choo-plc-eau-de-toilette-eau-de-parfum-fashion-jimmy-choo-cosmetics-perfume-fashion.png",
            inStock: 0,
            fastDelivery: true,
            ratings: 3,
        },
        {
            id: "48",
            brand: "Jimmy Choo",
            name: "Blossom",
            price: 69,
            desc: "Inspired by that first satisfying sip of a fruity cocktail, this sparkling scent opens with zesty berries and citrus – similar to mixologists favourite ingredients. Followed up by warming floral notes of rose and sweet pea, it transforms into a more demure, delicate concoction. And finally a musk and sandalwood base adds a seductive finishing touch.",
            imgSrc: "https://e7.pngegg.com/pngimages/53/891/png-clipart-perfume-eau-de-toilette-jimmy-choo-plc-cosmetics-designer-jimmy-choo-cosmetics-perfume.png",
            inStock: 7,
            fastDelivery: true,
            ratings: 4,
        },
        {
            id: "49",
            brand: "Jimmy Choo",
            name: "I Want Choo",
            price: 29,
            desc: "I Want Choo is a powerful oriental floral fragrance that explodes with joy and finishes with a seductive twist. Excitement and anticipation: a sparkling, citrus top note of Mandarin juice contrasts with velvety Peach nuances. Let the party begin: the sensual and solar Vanilla-like notes of Red.",
            imgSrc: "https://w7.pngwing.com/pngs/869/295/png-transparent-perfume-jimmy-choo-plc-eau-de-toilette-fashion-aftershave-perfume-miscellaneous-cosmetics-perfume.png",
            inStock: 0,
            fastDelivery: false,
            ratings: 2,
        },
        {
            id: "50",
            brand: "Jimmy Choo",
            name: "Jimmy Choo",
            price: 89,
            desc: "Glamorous in attitude, the fragrance is a modern Fruity Chypre with warm, rich, woody depths.Jimmy Choo Eau de Parfum expresses an aura of strength and beauty.",
            imgSrc: "https://w7.pngwing.com/pngs/648/598/png-transparent-perfume-eau-de-toilette-note-eau-de-parfum-sephora-perfume-miscellaneous-cosmetics-flower.png",
            inStock: 12,
            fastDelivery: true,
            ratings: 4,
        }
    ]

    const [state, dispatch] = useReducer(basketReducer, {
        products: products,
        basket: [],
    });

    const [productState, productDispatch] = useReducer(productReducer, {
        byStock: false,
        byFastDelivery: false,
        byRating: 0,
        searchQuery: "",
    });

    return (
        <Basket.Provider value={{state, dispatch, productState, productDispatch}}>
            { children }
        </Basket.Provider>
    )
}

export default Context;

export const BasketState = () => {
    return useContext(Basket)
}